name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.21.3'

      - name: Install dependencies
        run: npm install

      - name: Set environment variable for API key
        run: echo "REACT_APP_API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Set up Git authentication
        run: |
          git config --global credential.helper 'store --file=.git-credentials'
          echo "https://${{ secrets.ACTIONS_DEPLOY_KEY }}:x-oauth-basic@github.com" > .git-credentials
          git config --global user.name "Misha Kuptsov"
          git config --global user.email "azazin1955@gmail.com"

      - name: Check git remote configuration
        run: git remote -v

      - name: Build the project
        run: npm run build

      - name: Install gh-pages (if not already installed)
        run: npm install --save gh-pages

      - name: Deploy to GitHub Pages
        run: |
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
