name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Set up Git user
      run: |
        git config --global user.email "azazin1955@gmail.com"
        git config --global user.name "Misha Kuptsov"

    - name: Deploy to GitHub Pages
      run: |
        git checkout -b gh-pages
        
        cp -r build/* .

        git add -A

        git commit -m "Deploy to GitHub Pages"

        git push -f origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CI: false
